# Generated by Django 5.2.6 on 2025-09-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cardb',
            fields=[
                ('car_name', models.CharField(max_length=30)),
                ('regno', models.IntegerField(primary_key=True, serialize=False)),
                ('carowner_email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('mileage', models.FloatField()),
                ('colour', models.CharField(max_length=20)),
            ],
        ),
    ]
